language: python
python:
  - "3.8"

#services:
#  - postgresql
addons:
  postgresql: "11"
  apt:
    packages:
    - postgresql-11
    - postgresql-client-11

#before_script:
#  - psql -c 'create database travis_test;' -h localhost -U postgres

install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
script: pytest

env:
  global:
    - DATABASE_URL="postgres://postgres@localhost:5432/travis_test"
