language: python
python:
  - "3.8"

services:
  - postgresql

install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
script: pytest

env:
  global:
    - DATABASE_URL="postgres://postgres@localhost:5432/travis_test"

cache: pip
