language: python
python:
  - "3.8"
services:
  - postgresql
  -
addons:
  postgresql: "11"

install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
script: pytest

env:
  global:
    - DATABASE_URL="postgres://postgres@localhost:5432/jessdefiance"
