# Generated by Django 2.2.10 on 2020-04-20 10:46

import django.db.models.deletion
from django.db import migrations, models

from jessdefiance.blog.models import PostImage


def set_default_background_image():
    image = PostImage.objects.first()
    return image.id if image else 1


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200219_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='background_image',
            field=models.ForeignKey(default=set_default_background_image, on_delete=django.db.models.deletion.PROTECT, related_name='posts_with_background', to='blog.PostImage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
