# Generated by Django 2.2.10 on 2020-04-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200420_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('FASHION', 'Fashion'), ('TRENDS', 'Trends'), ('DEEPER', 'Deeper')], max_length=20),
        ),
    ]
